### PR TITLE
new version nr

### PR DESCRIPTION
**Pull request by k-freeman**
in order to tell whatsapp to use EndToEnd with yowsup clients.

### CODE REVIEW

**Comment by jlguardi** [comment]
Are _MD5_CLASSES and _KEY correct for this version?? I guess registration will fail.

**Comment by k-freeman** [comment]
ah sorry, didnt overcheck them, i thought changing the version number would be fine. (as for logins). did not test the registration. How do i get these values? greetings

**Comment by jlguardi** [comment]
I'll update as soon as all pending features were implemented.

**Comment by eduardobento** [comment]
Cool... EndToEnd message works. I dont try registration yet....

**Pull request closed without merging**
